
            var modelChilds = [
                        "instance",
                        "schema",
                        "submission",
                        "bind",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var instanceChilds = [];
            var bindChilds = [
                        "bind"];
            var extensionChilds = [];
            var labelChilds = [
                        "output"];
            var hintChilds = [
                        "output"];
            var helpChilds = [
                        "output"];
            var alertChilds = [
                        "output"];
            var itemChilds = [
                        "label",
                        "value",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var itemsetChilds = [
                        "label",
                        "value",
                        "copy",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var choicesChilds = [
                        "label",
                        "choices",
                        "item",
                        "itemset"];
            var valueChilds = [];
            var copyChilds = [];
            var inputChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var secretChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var textareaChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var uploadChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var filenameChilds = [];
            var mediatypeChilds = [];
            var select1Childs = [
                        "label",
                        "item",
                        "itemset",
                        "choices",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var selectChilds = [
                        "label",
                        "item",
                        "itemset",
                        "choices",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var rangeChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var triggerChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var outputChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var submitChilds = [
                        "label",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var repeatChilds = [
                        "input",
                        "secret",
                        "textarea",
                        "output",
                        "upload",
                        "select1",
                        "select",
                        "range",
                        "submit",
                        "trigger",
                        "group",
                        "switch",
                        "repeat",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var groupChilds = [
                        "label",
                        "input",
                        "secret",
                        "textarea",
                        "output",
                        "upload",
                        "select1",
                        "select",
                        "range",
                        "submit",
                        "trigger",
                        "group",
                        "switch",
                        "repeat",
                        "help",
                        "hint",
                        "alert",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var switchChilds = [
                        "label",
                        "input",
                        "secret",
                        "textarea",
                        "output",
                        "upload",
                        "select1",
                        "select",
                        "range",
                        "submit",
                        "trigger",
                        "group",
                        "switch",
                        "repeat",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var caseChilds = [
                        "label",
                        "input",
                        "secret",
                        "textarea",
                        "output",
                        "upload",
                        "select1",
                        "select",
                        "range",
                        "submit",
                        "trigger",
                        "group",
                        "switch",
                        "repeat",
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var actionChilds = [
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var setvalueChilds = [];
            var insertChilds = [];
            var deleteChilds = [];
            var setindexChilds = [];
            var toggleChilds = [];
            var setfocusChilds = [];
            var controlChilds = [];
            var dispatchChilds = [];
            var nameChilds = [];
            var targetidChilds = [];
            var targetChilds = [];
            var delayChilds = [];
            var rebuildChilds = [];
            var recalculateChilds = [];
            var revalidateChilds = [];
            var refreshChilds = [];
            var resetChilds = [];
            var loadChilds = [];
            var resourceChilds = [];
            var sendChilds = [];
            var messageChilds = [
                        "output"];
            var submissionChilds = [
                        "action",
                        "setvalue",
                        "insert",
                        "delete",
                        "setindex",
                        "toggle",
                        "setfocus",
                        "dispatch",
                        "rebuild",
                        "recalculate",
                        "revalidate",
                        "refresh",
                        "reset",
                        "load",
                        "send",
                        "message"];
            var methodChilds = [];
            var headerChilds = [];