/*
 * Copyright (c) 2012. betterFORM Project - http://www.betterform.de
 * Licensed under the terms of BSD License
 */



package de.betterform.xml.xforms.model;

import de.betterform.xml.events.DOMEventNames;
import de.betterform.xml.xforms.XFormsProcessorImpl;
import de.betterform.xml.xforms.exception.XFormsException;
import de.betterform.xml.xpath.impl.saxon.XPathUtil;
import junit.framework.TestCase;
import org.w3c.dom.Document;

/**
 * Do XForms models generated from HTML work?
 *
 * Uses GeneratedModelFromHTML.html which is assumed to be generated by html2xforms.xsl from well-formed HTML.
 */
public class GeneratedModelFromHTMLTest extends TestCase {
    static {
		org.apache.log4j.BasicConfigurator.configure();
	}

    private XFormsProcessorImpl xformsProcesssorImpl;
    private Document host;

    @Override
    protected void setUp() throws Exception {
        super.setUp();
    }

    public void testGeneratedTrackerModel() throws Exception{
        xformsProcesssorImpl = new XFormsProcessorImpl();
        this.xformsProcesssorImpl.setXForms(getClass().getResourceAsStream("GeneratedModelFromHTML.html"));
        xformsProcesssorImpl.init();
        host = xformsProcesssorImpl.getContainer().getDocument();
        assertNotNull(host);
        xformsProcesssorImpl.getContainer().getDefaultModel().recalculate();
    }

    @Override
    protected void tearDown() throws Exception {
        super.tearDown();
    }


}
