<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2011sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns0="urn:icit:greenery:orders" exclude-result-prefixes="xs fn">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_DESADV" as="node()?" select="ns0:DESADV"/>
		<DESADV xmlns="urn:icit:greenery:orders">
			<Envelop_Info>
				<xsl:for-each select="$var1_DESADV">
					<CompanyName>
						<xsl:sequence select="fn:string(ns0:Envelop_Info/ns0:CompanyName)"/>
					</CompanyName>
				</xsl:for-each>
				<xsl:for-each select="$var1_DESADV">
					<CompanyGLN>
						<xsl:sequence select="fn:string(ns0:Envelop_Info/ns0:CompanyGLN)"/>
					</CompanyGLN>
				</xsl:for-each>
				<MessageDateTime>
					<xsl:sequence select="xs:string(fn:current-dateTime())"/>
				</MessageDateTime>
				<MessageReference>
					<xsl:sequence select="''"/>
				</MessageReference>
			</Envelop_Info>
			<HeaderInfo>
				<xsl:for-each select="$var1_DESADV">
					<DeliveryType>
						<xsl:sequence select="fn:string(ns0:HeaderInfo/ns0:DeliveryType)"/>
					</DeliveryType>
				</xsl:for-each>
				<xsl:for-each select="$var1_DESADV">
					<EstimatedDateTimeOfArrival>
						<xsl:sequence select="xs:string(xs:dateTime(fn:string(ns0:HeaderInfo/ns0:EstimatedDateTimeOfArrival)))"/>
					</EstimatedDateTimeOfArrival>
				</xsl:for-each>
				<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:ContractNumber">
					<ContractNumber>
						<xsl:sequence select="fn:string(.)"/>
					</ContractNumber>
				</xsl:for-each>
				<BuyerOrderNumber>
					<xsl:sequence select="''"/>
				</BuyerOrderNumber>
				<xsl:for-each select="$var1_DESADV">
					<emailaddress>
						<xsl:sequence select="fn:string(ns0:HeaderInfo/ns0:emailaddress)"/>
					</emailaddress>
				</xsl:for-each>
				<Incoterms>
					<cfr>
						<xsl:variable name="var2_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cfr">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var2_let)">
									<xsl:sequence select="$var2_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var3_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cfr">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var3_let)">
									<xsl:sequence select="$var3_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</cfr>
					<cif>
						<xsl:variable name="var4_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cif">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var4_let)">
									<xsl:sequence select="$var4_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var5_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cif">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var5_let)">
									<xsl:sequence select="$var5_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</cif>
					<cip>
						<xsl:variable name="var6_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cip">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var6_let)">
									<xsl:sequence select="$var6_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var7_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cip">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var7_let)">
									<xsl:sequence select="$var7_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</cip>
					<cpt>
						<xsl:variable name="var8_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cpt">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var8_let)">
									<xsl:sequence select="$var8_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var9_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:cpt">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var9_let)">
									<xsl:sequence select="$var9_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</cpt>
					<dap>
						<xsl:variable name="var10_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:dap">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var10_let)">
									<xsl:sequence select="$var10_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var11_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:dap">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var11_let)">
									<xsl:sequence select="$var11_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</dap>
					<dat>
						<xsl:variable name="var12_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:dat">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var12_let)">
									<xsl:sequence select="$var12_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var13_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:dat">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var13_let)">
									<xsl:sequence select="$var13_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</dat>
					<ddp>
						<xsl:variable name="var14_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:ddp">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var14_let)">
									<xsl:sequence select="$var14_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var15_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:ddp">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var15_let)">
									<xsl:sequence select="$var15_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</ddp>
					<exw>
						<xsl:variable name="var16_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:exw">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var16_let)">
									<xsl:sequence select="$var16_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var17_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:exw">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var17_let)">
									<xsl:sequence select="$var17_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</exw>
					<fas>
						<xsl:variable name="var18_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:fas">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var18_let)">
									<xsl:sequence select="$var18_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var19_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:fas">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var19_let)">
									<xsl:sequence select="$var19_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</fas>
					<fca>
						<xsl:variable name="var20_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:fca">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var20_let)">
									<xsl:sequence select="$var20_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var21_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:fca">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var21_let)">
									<xsl:sequence select="$var21_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</fca>
					<fob>
						<xsl:variable name="var22_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:fob">
								<xsl:sequence select="fn:string(ns0:Incoterm)"/>
							</xsl:for-each>
						</xsl:variable>
						<Incoterm>
							<xsl:choose>
								<xsl:when test="fn:exists($var22_let)">
									<xsl:sequence select="$var22_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Incoterm>
						<xsl:variable name="var23_let" as="xs:string?">
							<xsl:for-each select="$var1_DESADV/ns0:HeaderInfo/ns0:Incoterms/ns0:fob">
								<xsl:sequence select="fn:string(ns0:Place)"/>
							</xsl:for-each>
						</xsl:variable>
						<Place>
							<xsl:choose>
								<xsl:when test="fn:exists($var23_let)">
									<xsl:sequence select="$var23_let"/>
								</xsl:when>
								<xsl:otherwise>
									<xsl:sequence select="''"/>
								</xsl:otherwise>
							</xsl:choose>
						</Place>
					</fob>
				</Incoterms>
				<xsl:for-each select="$var1_DESADV">
					<webmastermail>
						<xsl:sequence select="xs:string(xs:anyURI(fn:string(ns0:HeaderInfo/ns0:webmastermail)))"/>
					</webmastermail>
				</xsl:for-each>
			</HeaderInfo>
			<xsl:for-each select="$var1_DESADV">
				<xsl:variable name="var24_HeaderAddresses" as="node()" select="ns0:HeaderAddresses"/>
				<HeaderAddresses>
					<xsl:sequence select="($var24_HeaderAddresses/@node(), $var24_HeaderAddresses/node())"/>
				</HeaderAddresses>
			</xsl:for-each>
			<Consignment>
				<xsl:for-each select="$var1_DESADV">
					<xsl:variable name="var25_LineInfos" as="node()" select="ns0:Consignment/ns0:LineInfos"/>
					<LineInfos>
						<xsl:sequence select="($var25_LineInfos/@node(), $var25_LineInfos/node())"/>
					</LineInfos>
				</xsl:for-each>
			</Consignment>
		</DESADV>
	</xsl:template>
</xsl:stylesheet>
